const { Router } = require('express')
const studentController = require('../controllers/studentController')
const { verifyTokenAuth } = require('../middleware/auth')
const router = Router()
router.get('/students', verifyTokenAuth, studentController.listStudents)
router.put('/students/:id', verifyTokenAuth, studentController.editStudent)
router.delete('/students/:id', verifyTokenAuth, studentController.deleteStudent)
router.post('/sectionStudent/:id', verifyTokenAuth, studentController.addStudentToSection)
router.delete('/sectionStudent/:id', verifyTokenAuth, studentController.deleteStudentFromSection)
module.exports = router